# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI build

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu' # Alternative distribution options are available.
        cache: maven

# Jfrog artifactory
    - name: Login, build, tag and push to jfrog
      run: |
          docker login -u ${{ JFROG_REGISTRY_USERNAME }} -p ${{ JFROG_REGISTRY_PASSWORD }} a0mb6i6yarojf.jfrog.io
          docker build . -t a0mb6i6yarojf.jfrog.io/gitaction-jrog-repo/first-jfrog-image:${{ github.run_number }}
          docker push a0mb6i6yarojf.jfrog.io/gitaction-jrog-repo/first-jfrog-image:${{ github.run_number }}

